"""Report generation (HTML content + PDF via ReportLab).

Reports never include passwords, API keys, tokens or secrets — the report
builder only draws from domain data (events, incidents, vulnerabilities,
hardening findings) and the analyst profile (username/role).
"""
from __future__ import annotations

import io
import logging
from datetime import datetime, timezone
from html import escape
from typing import Any

from sqlalchemy.orm import Session

from app.models import (
    Host,
    Incident,
    SecurityEvent,
    Scan,
    User,
    Vulnerability,
    WazuhAlert,
)

logger = logging.getLogger("mlinziops.reports")


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _severity_score(sev: str) -> int:
    return {"INFO": 0, "LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}.get(sev, -1)


def _counts(rows: list[Any], attr: str = "severity") -> dict[str, int]:
    out: dict[str, int] = {}
    for r in rows:
        key = getattr(r, attr, "INFO")
        out[key] = out.get(key, 0) + 1
    return out


def build_report_payload(db: Session, analyst: User, title: str, scope: str | None,
                         summary: str | None, host_ids: list[int] | None) -> dict[str, Any]:
    """Assemble every section backing a report."""
    now = utcnow()

    hosts_q = db.query(Host)
    if host_ids:
        hosts_q = hosts_q.filter(Host.id.in_(host_ids))
    hosts = hosts_q.all()

    events_q = db.query(SecurityEvent)
    incidents = db.query(Incident).all()
    vulnerabilities = db.query(Vulnerability).all()
    wazuh_alerts = db.query(WazuhAlert).all()
    scans = db.query(Scan).order_by(Scan.started_at.desc()).limit(20).all()

    # Host-scoped events where possible: attach source_ip to registered hosts
    host_ips = {h.ip_address for h in hosts}
    if host_ips:
        events_q = events_q.filter(SecurityEvent.source_ip.in_(host_ips))
    events = events_q.order_by(SecurityEvent.timestamp.desc()).limit(500).all()
    events = list(events)

    sev_counts = _counts(events)
    vuln_counts = _counts(vulnerabilities)

    high_events = [e for e in events if _severity_score(e.severity) >= 3]

    sections = [
        ("Executive Summary", paragraphs(summary or f"Security assessment generated by {analyst.username} ({analyst.role}).")),
        ("Scope", paragraphs(scope or "All registered hosts within the authorized lab scope.")),
        ("Hosts Assessed", hosts_table(hosts)),
        ("Network Services", services_table(hosts, scans, db)),
        ("Security Events", events_summary_table(events, sev_counts)),
        ("Detected Patterns", detected_patterns(events)),
        ("Wazuh Alerts", wazuh_table(wazuh_alerts)),
        ("Incidents", incidents_table(incidents)),
        ("Potential Vulnerabilities", vuln_table(vulnerabilities, vuln_counts)),
        ("Hardening Findings", hardening_table()),
        ("Recommendations", recommendations(high_events, vuln_counts, hosts)),
        ("Conclusion", paragraphs(conclusion_text())),
    ]

    web_sections = []
    for name, html in sections:
        web_sections.append({"name": name, "html": html})

    return {
        "generated_at": now.isoformat(),
        "analyst": analyst.username,
        "analyst_role": analyst.role,
        "title": title,
        "scope": scope,
        "hosts": len(hosts),
        "events": len(events),
        "incidents": len(incidents),
        "vulnerabilities": len(vulnerabilities),
        "sev_counts": sev_counts,
        "sections": web_sections,
        "wazuh_alerts": len(wazuh_alerts),
    }


def _truncate(s: str | None, n: int = 120) -> str:
    if not s:
        return ""
    s = s.replace("\n", " ")
    return s if len(s) <= n else s[: n - 3] + "..."


def paragraphs(text: str) -> str:
    return f"<p>{escape(text)}</p>"


def hosts_table(hosts: list[Host]) -> str:
    rows = "".join(
        f"<tr><td>{escape(h.hostname)}</td><td>{escape(h.ip_address)}</td>"
        f"<td>{escape(h.operating_system or '')}</td><td>{escape(h.environment)}</td>"
        f"<td>{escape(h.status)}</td></tr>"
        for h in hosts
    )
    if not rows:
        return "<p>No hosts within scope.</p>"
    return table_html(["Hostname", "IP", "OS", "Environment", "Status"], rows)


def services_table(hosts: list[Host], scans: list[Scan], db: Session) -> str:
    from app.models import ScanService

    body = ""
    if scans:
        seen = set()
        for scan in scans:
            for svc in scan.services:
                key = (scan.target, svc.port, svc.protocol)
                if key in seen:
                    continue
                seen.add(key)
                body += (
                    f"<tr><td>{escape(scan.target)}</td><td>{svc.port}/{svc.protocol}</td>"
                    f"<td>{svc.state}</td><td>{escape(svc.service or '')}</td>"
                    f"<td>{escape((svc.product or '') + ' ' + (svc.version or ''))}</td></tr>"
                )
    if not body:
        body = "<tr><td colspan='5'>No scan data yet — run an authorized service scan.</td></tr>"
    return table_html(["Host", "Port", "State", "Service", "Product/Version"], body)


def events_summary_table(events: list[SecurityEvent], counts: dict[str, int]) -> str:
    rows = "".join(
        f"<tr><td>{sev}</td><td>{counts.get(sev, 0)}</td></tr>"
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")
    )
    recent = "".join(
        f"<tr><td>{e.timestamp.isoformat()}</td><td>{escape(e.event_type)}</td>"
        f"<td>{escape(e.source_ip or '')}</td><td>{escape(e.username or '')}</td>"
        f"<td>{e.severity}</td><td>{escape(_truncate(e.description))}</td></tr>"
        for e in events[:30]
    )
    if not recent:
        recent = "<tr><td colspan='6'>No events found.</td></tr>"
    return (
        table_html(["Severity", "Count"], rows)
        + "<h4 class='report-sub'>Recent events (top 30)</h4>"
        + table_html(["Timestamp", "Type", "Source IP", "User", "Severity", "Description"], recent)
    )


def detected_patterns(events: list[SecurityEvent]) -> str:
    detections = [e for e in events if e.category == "detection" or "brute" in e.event_type.lower()]
    rows = "".join(
        f"<tr><td>{e.timestamp.isoformat()}</td><td>{escape(e.event_type)}</td>"
        f"<td>{e.severity}</td><td>{escape(e.source_ip or '')}</td>"
        f"<td>{escape(_truncate(e.description))}</td></tr>"
        for e in detections[:50]
    )
    if not rows:
        return "<p>No detection-engine patterns fired in the analyzed window.</p>"
    return table_html(["Timestamp", "Pattern", "Severity", "Source", "Description"], rows)


def wazuh_table(alerts: list[WazuhAlert]) -> str:
    rows = "".join(
        f"<tr><td>{a.timestamp.isoformat()}</td><td>{escape(a.rule_id or '')}</td>"
        f"<td>{a.level or ''}</td><td>{escape(a.agent_name or '')}</td>"
        f"<td>{escape(a.srcip or '')}</td><td>{escape(_truncate(a.rule_description or ''))}</td></tr>"
        for a in alerts[:50]
    )
    if not rows:
        return "<p>No Wazuh alerts available (Wazuh disconnected or no alerts ingested).</p>"
    return table_html(["Timestamp", "Rule", "Level", "Agent", "Source IP", "Description"], rows)


def incidents_table(incidents: list[Incident]) -> str:
    rows = "".join(
        f"<tr><td>{escape(i.incident_number)}</td><td>{escape(i.title)}</td>"
        f"<td>{i.severity}</td><td>{i.status}</td><td>{escape(i.assigned_to or '')}</td>"
        f"<td>{i.created_at.isoformat()}</td></tr>"
        for i in incidents
    )
    if not rows:
        return "<p>No incidents.</p>"
    return table_html(["ID", "Title", "Severity", "Status", "Assignee", "Created"], rows)


def vuln_table(vulns: list[Vulnerability], counts: dict[str, int]) -> str:
    rows = "".join(
        f"<tr><td>{escape(v.host)}</td><td>{v.port or ''}</td>"
        f"<td>{escape(v.service or '')}</td><td>{escape(v.software or '')}</td>"
        f"<td>{escape(v.version or '')}</td><td>{escape(v.cve or '')}</td>"
        f"<td>{v.severity}</td><td>{v.status}</td>"
        f"<td>{escape(_truncate(v.description or '') )}</td></tr>"
        for v in vulns
    )
    summary = "".join(
        f"<tr><td>{sev}</td><td>{counts.get(sev, 0)}</td></tr>"
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")
    )
    if not rows:
        rows = "<tr><td colspan='9'>No vulnerability records. Matching is version-based and requires validation.</td></tr>"
    return table_html(["Severity", "Count"], summary) + table_html(
        ["Host", "Port", "Service", "Software", "Version", "CVE", "Severity", "Status", "Description"],
        rows,
    )


def hardening_table() -> str:
    """Include read-only hardening check results (best-effort, current host)."""
    try:
        from app.services.security_checks import run_checks

        checks = run_checks()
    except Exception:  # checks must never break report generation
        logger.exception("Hardening checks failed during report build")
        return "<p>Hardening checks unavailable at generation time.</p>"
    if not checks:
        return "<p>No hardening checks returned results.</p>"
    rows = "".join(
        f"<tr><td>{escape(c['status'])}</td><td>{escape(c['title'])}</td>"
        f"<td>{escape(_truncate(c['detail'], 180))}</td>"
        f"<td>{escape(_truncate(c['remediation'], 160))}</td></tr>"
        for c in checks
    )
    return table_html(["Result", "Check", "Detail", "Remediation"], rows)


def recommendations(high_events: list[SecurityEvent], vuln_counts: dict[str, int], hosts: list[Host]) -> str:
    items: list[str] = []
    if high_events:
        items.append("Investigate the HIGH/CRITICAL security events listed above — begin with source IPs showing repeated authentication failures.")
    high_vulns = vuln_counts.get("HIGH", 0) + vuln_counts.get("CRITICAL", 0)
    if high_vulns:
        items.append(f"Prioritize patching {high_vulns} HIGH/CRITICAL potential vulnerabilities (validate versions before confirming).")
    offline = [h.hostname for h in hosts if h.status == "OFFLINE"]
    if offline:
        items.append(f"Check why hosts appear offline: {', '.join(offline[:5])}.")
    items.append("Verify each open service against the approved service baseline and disable unneeded services.")
    items.append("Enforce key-based SSH authentication and disable root login where possible.")
    items.append("Re-run this assessment after remediation and compare results.")
    return "<ul>" + "".join(f"<li>{escape(i)}</li>" for i in items) + "</ul>"


def conclusion_text() -> str:
    return (
        "This assessment reflects data collected from the authorized lab scope at report "
        "generation time. Findings are indicators requiring validation, not confirmed "
        "vulnerabilities or compromises. The MlinziOps audit trail records who generated "
        "this report and when."
    )


def table_html(headers: list[str], body: str) -> str:
    head = "".join(f"<th>{escape(h)}</th>" for h in headers)
    return f"<table class='report-table'><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


# ---------------------------------------------------------------------------
# PDF rendering (ReportLab). Text-only, professional layout.
# ---------------------------------------------------------------------------
def render_pdf(payload: dict[str, Any]) -> bytes:
    """Render a report payload to a PDF byte stream."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=18 * mm, bottomMargin=18 * mm,
                            title=payload["title"])
    styles = getSampleStyleSheet()
    story: list[Any] = []

    story.append(Paragraph("MlinziOps Security Assessment", styles["Title"]))
    story.append(Paragraph(payload["title"], styles["Heading2"]))
    story.append(Spacer(1, 4 * mm))
    meta = [
        ["Report ID", f"{payload.get('report_number', 'RPT-XXXX')}"],
        ["Date (UTC)", payload["generated_at"]],
        ["Analyst", payload["analyst"]],
        ["Analyst role", payload["analyst_role"]],
        ["Scope", payload.get("scope") or "All registered hosts"],
    ]
    story.append(_pdf_table(meta, styles))
    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#8892a6")))

    for section in payload["sections"]:
        story.append(Spacer(1, 5 * mm))
        story.append(Paragraph(section["name"], styles["Heading2"]))
        story.extend(_html_to_pdf_blocks(section["html"], styles))

    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#8892a6")))
    story.append(Paragraph("Generated by MlinziOps. Contains no credentials or secrets.", styles["Italic"]))

    doc.build(story)
    return buf.getvalue()


def _pdf_table(rows: list[list[str]], styles: Any) -> Any:
    from reportlab.lib import colors
    from reportlab.platypus import Table, TableStyle

    t = Table(rows, colWidths=[40 * 2.83, 120 * 2.83])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#8892a6")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f2f4f8")),
        ("PADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _html_to_pdf_blocks(html: str, styles: Any) -> list[Any]:
    """Convert the limited HTML we emit into reportlab paragraphs/tables."""
    from xml.etree import ElementTree as ET
    from reportlab.platypus import Paragraph, Table, TableStyle
    from reportlab.lib import colors

    blocks: list[Any] = []
    try:
        root = ET.fromstring(f"<div>{html}</div>")
    except ET.ParseError:
        return [Paragraph("(content unavailable)", styles["BodyText"])]

    def walk(el: ET.Element) -> None:
        for child in el:
            tag = child.tag.lower()
            if tag == "p":
                text = "".join(child.itertext())
                blocks.append(Paragraph(text, styles["BodyText"]))
            elif tag == "table":
                header = []
                rows = []
                for i, tr in enumerate(child.findall(".//tr")):
                    cells = ["".join(td.itertext()).strip() for td in tr.findall("td") or tr.findall("th")]
                    # tr can be direct child of thead/tbody
                    if not cells:
                        continue
                    if i == 0 and not header:
                        header = cells
                    else:
                        rows.append(cells)
                if header:
                    data = [header] + rows
                else:
                    data = rows
                if data:
                    t = Table(data)
                    t.setStyle(TableStyle([
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
                        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#8892a6")),
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef1f5")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 3),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f9fb")]),
                    ]))
                    blocks.append(t)
            elif tag in ("h3", "h4"):
                text = "".join(child.itertext())
                blocks.append(Paragraph(text, styles["Heading3"]))
            else:
                walk(child)

    walk(root)
    return blocks
