"""Incident + reporting tools. READ_ONLY / MEDIUM_RISK (data writes)."""
from __future__ import annotations

from app.ai.registry import Tool, registry
from app.constants import RISK_MEDIUM


def register() -> None:
    registry.register(Tool(
        name="create_incident",
        description="Create an incident record (MEDIUM_RISK data write).",
        risk_level=RISK_MEDIUM,
        input_schema={
            "type": "object",
            "properties": {
                "title": {"type": "string", "minLength": 3, "maxLength": 255},
                "severity": {"type": "string", "enum": ["LOW", "MEDIUM", "HIGH", "CRITICAL"]},
                "description": {"type": "string", "maxLength": 4000},
            },
            "required": ["title"],
            "additionalProperties": False,
        },
        handler=_create_incident,
        timeout_seconds=15.0,
        authorization="analyst",
        requires_approval=True,
    ))
    registry.register(Tool(
        name="add_investigation_note",
        description="Append an investigation note to an incident.",
        risk_level=RISK_MEDIUM,
        input_schema={
            "type": "object",
            "properties": {
                "incident_id": {"type": "integer"},
                "note": {"type": "string", "maxLength": 4000},
            },
            "required": ["incident_id", "note"],
            "additionalProperties": False,
        },
        handler=_add_note,
        timeout_seconds=15.0,
        authorization="analyst",
        requires_approval=True,
    ))
    registry.register(Tool(
        name="generate_report",
        description="Generate a security assessment report (MEDIUM_RISK data write).",
        risk_level=RISK_MEDIUM,
        input_schema={
            "type": "object",
            "properties": {
                "title": {"type": "string", "maxLength": 255},
                "scope": {"type": "string", "maxLength": 2000},
            },
            "additionalProperties": False,
        },
        handler=_generate_report,
        timeout_seconds=60.0,
        authorization="analyst",
        requires_approval=True,
    ))


async def _create_incident(params: dict) -> dict:
    from app.database import SessionLocal
    from app.models import Incident

    with SessionLocal() as db:
        last = db.query(Incident).order_by(Incident.id.desc()).first()
        number = f"INC-{(last.id + 1) if last else 1:04d}"
        inc = Incident(
            incident_number=number,
            title=params["title"],
            severity=params.get("severity", "MEDIUM"),
            description=params.get("description"),
            source="ai-agent",
            assigned_to="ai-analyst",
        )
        db.add(inc)
        db.commit()
        db.refresh(inc)
        return {"incident_id": inc.id, "incident_number": inc.incident_number}


async def _add_note(params: dict) -> dict:
    from app.database import SessionLocal
    from app.models import Incident, IncidentNote

    with SessionLocal() as db:
        inc = db.get(Incident, int(params["incident_id"]))
        if inc is None:
            raise ValueError("incident not found")
        note = IncidentNote(
            incident_id=inc.id,
            analyst="ai-agent",
            action="AI_NOTE",
            note=str(params["note"])[:4000],
        )
        db.add(note)
        db.commit()
        return {"note_id": note.id}


async def _generate_report(params: dict) -> dict:
    from app.database import SessionLocal
    from app.models import Report, User
    from app.services import report_generator

    title = params.get("title") or "AI Security Assessment"
    with SessionLocal() as db:
        admin = db.query(User).filter(User.role == "ADMIN").first()
        last = db.query(Report).order_by(Report.id.desc()).first()
        number = f"RPT-{(last.id + 1) if last else 1:04d}"
        payload = report_generator.build_report_payload(
            db, admin, title, params.get("scope"), "Generated by the AI analyst.", None
        )
        from app.api.reports import _payload_to_html  # local to avoid cycle

        report = Report(
            report_number=number,
            title=title,
            scope=params.get("scope"),
            summary="Generated by the AI analyst.",
            format="pdf",
            status="COMPLETED",
            content_html=_payload_to_html(payload),
            created_by_id=admin.id if admin else None,
        )
        db.add(report)
        db.commit()
        db.refresh(report)
        payload["report_number"] = number
        return {"report_id": report.id, "report_number": number}
    # Note: PDF bytes are generated on demand via the /reports/{id}/pdf endpoint.


register()
